// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blopjzszhewzjlubvktk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb3BqenN6aGV3empsdWJ2a3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTY1NTksImV4cCI6MjA3MzUzMjU1OX0.69NRCsG0BDbQJE0eSCZYO3aSZUH5BZedan98Yb3h9dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});